#!/bin/bash

docker_image="datascience-gpu"
declare -a mount_folders_arg

function show_usage() {
	printf "Usage $0: [options [parameters]]\n"
	printf "\n"
	printf "Options:\n"
	#printf "-D|--disable_gpu, Run container without GPU support\n"
	printf "-m|--mount path+[,path], mount host paths in docker.\n"
	printf "-h|--help, Display help.\n"
	return 0
}

function parse_folder_arg() {
	echo "Mounting:"
        mount_folders=("$@")
	dst_parent_folder="/rapids/host"
	for i in "${mount_folders[@]}"; do
		j="$(basename -- $i)"
        	echo "\t- $i:$dst_parent_folder/$j"
		mount_folders_arg+=("-v")
		mount_folders_arg+=("$i:$dst_parent_folder/$j")
        done
}

while [ ! -z "$1" ]; do
	if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
		show_usage
	#elif [[ "$1" == "--disable_gpu" ]] || [[ "$1" == "-D" ]]; then
	#	echo "Run container without GPU support"
	#	docker_image="datascience-cpu"
	elif [[ "$1" == "--mount" ]] || [[ "$1" == "-m" ]]; then
		my_string="Ubuntu;Linux Mint;Debian;Arch;Fedora"
		IFS=',' read -ra mount_folders <<< "$2"
		parse_folder_arg "${mount_folders[@]}"
		shift
	else
		echo "Incorrect input provided: $1"
	fi
	shift
done
#echo "${mount_folders_arg[@]}"
sudo docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 -v "$HOME/projects/notebooks:/rapids/host/notebooks" "${mount_folders_arg[@]}" "$docker_image"
